site_name: APOCFLY模拟飞行·文档站
site_url: https://www.apocfly.com
site_description: Use Markdown language to finish the Operating document.
repo_url: https://github.com/Flyleague-Collection/Operating-document
repo_name: Flyleague-Collection/Operating-document
edit_uri: edit/main/docs/

theme:
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil 
    view: material/eye
  features:
    - navigation.path
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tracking
    # - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.prune
    # - navigation.indexes  # 开启DIY导航栏
    # - toc.follow
    # - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - navigation.footer
    - content.action.edit
    # code
    # - content.code.select  # sponsors only
    - content.code.copy
    - content.code.annotate

  favicon: images/favicon.png
  name: material
  language: zh
  font:
    text: Roboto
    code: Roboto Mono
  logo: assets/Logo.png
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
        
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
extra:
  generator: true
  homepage: https://www.apocfly.com
  # version:
    # provider: mike
    # default: stable
    # alias: true
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Flyleague-Collection/Operating-document
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/3494374067407653
    - icon: fontawesome/brands/tiktok
      link: https://v.douyin.com/97uoxOsUrcA
    - icon: fontawesome/brands/qq
      link: https://qm.qq.com/q/5qyq2c4n9m
    
  scope: /

markdown_extensions:
  - md_in_html
  # - attr_list
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences


# nav:
  # - 开发:
    # - 
  # - 主页: 
  #   - index.md
  # - 许可证: 
  #   - license.md



plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
  - git-committers:
      repository: Flyleague-Collection/Operating-document
      branch: main
      token: !!python/object/apply:os.getenv ["MKDOCS_GIT_COMMITTERS_APIKEY"]
  # - info
  # - privacy
  # - tags

  # - blog  # 播客 插件(可能导致兼容性错误)

      # token: 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
  # - projects
  # - optimize
  # - offline

    
  # - social
  # - tags
  
copyright: 本项目的全部文字在 <a href="https://creativecommons.org/licenses/by-sa/4.0/deed.zh-hans" target="_blank" rel="noopener noreferrer">CC BY-SA 4.0(知识共享 署名-相同方式共享 4.0协议)</a> 之条款下提供，附加条款亦可能应用。<br> Yiheng Master Gui 保留所有未明示授予的权利。
